# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    # - bash: echo $(PipelineLevelVariable)
    # - bash: echo BuildNumber:$(Build.BuildNumber)
    # - bash: echo BuildId:$(Build.BuildId)
    # - bash: echo SourceBranchName:$(Build.SourceBranchName)
    # - bash: echo SourcesDirectory:$(Build.SourcesDirectory)
    # - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    # - bash: echo DefaultWorkingDirectory:$(Build.DefaultWorkingDirectory)
    # - bash: ls -R $(System.DefaultWorkingDirectory)

    - bash: java -version
    - bash: mvn -version
    - bash: node --version
    - bash: python --version

    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)

  - job: SecondJob
    steps:
    - bash: echo Build/SecondJob



# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     environment: DevDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(environment)/FirstJob
  
#   - job: SecondJob
#     steps:
#     - bash: echo DevDeploy/SecondJob



# - stage: QADeploy
#   dependsOn: Build
#   variables:
#     environment: QADeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(envitonment)/FirstJob

#   - job: SecondJob
#     steps:
#     - bash: echo QADeploy/SecondJob


# - stage: ProdDeploy
#   dependsOn:
#   - QADeploy
#   - DevDeploy
#   variables:
#     environment: ProdDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(envitonment)/FirstJob

#   - job: SecondJob
#     steps:
#     - bash: echo ProdDeploy/SecondJob

