trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'
#     windows:
#       operatingSystem: 'windows-latest'

# pool:
#   vmImage: $(operatingSystem)

# steps:
# - script: echo Running on $(operatingSystem)!
#   displayName: 'Run a one-line script'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo 'Do the Build'

- stage: DevDeploy
  jobs:
  # - job: DevDeploy
  #   steps:
  #   - bash: echo 'Start DevDeploy'
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev

- stage: QADeploy
  jobs:
  - job: QADeploy
    steps:
    - bash: echo 'Start DevDeploy'
  # - deployment: QADeployJob
  #   environment: QA
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - script: echo deploy to QA

# job and deployment are both jobs but deployment has more attributes
